### ISSUE TITLE
Quickstart/Getting Started Document

### ISSUE THREAD

**Issue by drharper** [HPFOD/FoDBugTrackerUtility#11]
Walkthrough how to do an initial install and test of the utility and then point them at the wiki for more details.

**Comment by drharper** [comment]
Draft attached
[FoDBugTrackerUtility DRAFT.docx](https://github.com/ryancblack/FoDBugTrackerUtility/files/383879/FoDBugTrackerUtility.DRAFT.docx)

**Comment by drharper** [comment]
[FoD Explained - FoDBugTrackerUtility.pdf](https://github.com/HPFOD/FoDBugTrackerUtility/files/417812/FoD.Explained.-.FoDBugTrackerUtility.pdf)
[FoDBugTrackerUtility.docx](https://github.com/HPFOD/FoDBugTrackerUtility/files/417811/FoDBugTrackerUtility.docx)

Next version attached

**Comment by ryancblack** [comment]
Added to release.
