### ISSUE TITLE
Incorrect links in Wiki pages

### ISSUE THREAD

**Issue by rsenden** [HPFOD/FoDBugTrackerUtility#12]
Vaious wiki pages still point at ryancblack instead of HPFOD. For example, the home Wiki page contains a link to https://github.com/ryancblack/FoDBugTrackerUtility/releases instead of https://github.com/HPFOD/FoDBugTrackerUtility/releases

**Comment by ryancblack** [comment]
Thanks Ruud, I intend to fix those remnants of the transfer of the repo once we finalize the Wiki entries around usage (-showversion requirement, etc.)

**Comment by ryancblack** [comment]
@drharper  - can you please look over the Wiki for approval?

**Comment by ryancblack** [comment]
Wiki links updated.
