### ISSUE TITLE
Use of 5.2 bug tracker link field

### ISSUE THREAD

**Issue by drharper** [HPFOD/FoDBugTrackerUtility#13]
With FoD 5.2 an additional field has been added to store the bug-tracker link information. This field is not available through the FoD API and so cannot be used by the FoDBugTracker Utility. 

If this field is made available in the API  in a future FoD release the utility should be modified to use it instead of the comments field.

**Comment by rsenden** [comment]
Based on configuration, FoDBugTrackerUtility now supports storing the bug link in either an FoD comment (as before) or in the FoD bugLink field.
