### ISSUE TITLE
Track Java bug 8132379 impacting command line

### ISSUE THREAD

**Issue by ryancblack** [HPFOD/FoDBugTrackerUtility#16]
Currently we must use `-showversion` at the command line to work around an existing defect in many Java versions that causes a JRE crash if the application uses arguments beginning with the character 'J' when we have a better workaround, or can otherwise remove this, we'll close this issue. 

See:  [here ](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8132379)

**Comment by rsenden** [comment]
FoDBugTrackerUtility now allows context properties to be specified on the command line with either one or two dashes (i.e. -JiraBaseURL or --JiraBaseUrl); using two dashes for affected options will avoid the JRE crash.
