### ISSUE TITLE
QA Testing

### ISSUE THREAD

**Issue by rsenden** [HPFOD/FoDBugTrackerUtility#9]
So far only limited tests have been performed; proper QA testing should still be done.

Some examples of things to test:

- Check all available process runner configurations for correct operation:
  - Correct set of vulnerabilities retrieved from FoD (based on filter settings)
  - Correct vulnerability data submitted to bug tracker/file (id's, severity, deep link, ...)
  - Vulnerabilities grouped correctly
  - All command line option combinations work as expected
- Check correct proxy operation by executing process runners with and without proxy settings
- Check error handling

**Comment by ryancblack** [comment]
Thus far testing has been successful under multiple configuration cases, closing task.
